//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34011
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ccbatest.CcbaService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CcbaService.ICcbaService")]
    public interface ICcbaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICcbaService/DoWork", ReplyAction="http://tempuri.org/ICcbaService/DoWorkResponse")]
        string DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICcbaService/GetServerTime", ReplyAction="http://tempuri.org/ICcbaService/GetServerTimeResponse")]
        System.DateTime GetServerTime(int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICcbaService/GetTable", ReplyAction="http://tempuri.org/ICcbaService/GetTableResponse")]
        System.Data.DataTable GetTable(string Sqlstr, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICcbaService/ExecSQL", ReplyAction="http://tempuri.org/ICcbaService/ExecSQLResponse")]
        int ExecSQL(string Sqlstr, int uid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICcbaService/ExecuteScalar", ReplyAction="http://tempuri.org/ICcbaService/ExecuteScalarResponse")]
        object ExecuteScalar(string Sqlstr, int uid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICcbaServiceChannel : ccbatest.CcbaService.ICcbaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CcbaServiceClient : System.ServiceModel.ClientBase<ccbatest.CcbaService.ICcbaService>, ccbatest.CcbaService.ICcbaService {
        
        public CcbaServiceClient() {
        }
        
        public CcbaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CcbaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CcbaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CcbaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string DoWork() {
            return base.Channel.DoWork();
        }
        
        public System.DateTime GetServerTime(int uid) {
            return base.Channel.GetServerTime(uid);
        }
        
        public System.Data.DataTable GetTable(string Sqlstr, int uid) {
            return base.Channel.GetTable(Sqlstr, uid);
        }
        
        public int ExecSQL(string Sqlstr, int uid) {
            return base.Channel.ExecSQL(Sqlstr, uid);
        }
        
        public object ExecuteScalar(string Sqlstr, int uid) {
            return base.Channel.ExecuteScalar(Sqlstr, uid);
        }
    }
}
